apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  labels:
    name: gateway
    type: microservice
spec:
  containers:
  - name: gateway-app
    image: danielml/microservice-gateway:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
