apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    name: microservice-seguridad
    type: microservice
spec:
  containers:
  - name: microservice-seguridad-app
    image: danielml/microservice-seguridad:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: ConnectionStrings__ConexionDB
        value: Server=mssql-service;Database=seguridad;User=sa;Password:$root2025
