apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-seguridad-deploy
  labels:
    name: microservice-seguridad-deploy
    app: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      name: microservice-seguridad
      type: microservice
  template:
    metadata:
      name: microservice-seguridad-pod
      labels:
        name: microservice-seguridad
        type: microservice
    spec:
      containers:
      - name: microservice-seguridad-app
        image: danielml/microservice-seguridad:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          - name: ConnectionStrings__ConexionDB
            value: Server=mssql-service;Database=seguridad;User=sa;Password:$root2025