apiVersion: v1
kind: Pod
metadata:
  name: microservice-libreria-pod
  labels:
    name: microservice-libreria
    type: microservice
spec:
  containers:
  - name: microservice-libreria-app
    image: danielml/microservice-libreria:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: MongoDb__ConnectionString
        value: mongodb//danielml:$root2024@mongo-service:27017